### ISSUE TITLE
Bug generating the UC Master Comment Report

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-data-tech#22228]

**Comment by TracyLinder** [comment]
@Nadin-Nader will submit a CTM-SN ticket.

**Comment by Nadin-Nader** [comment]
@SubhaShroff @vschandramouli @TracyLinder Incident to fix file path has been submitted to CTM **INC0489907**

**Comment by TracyLinder** [comment]
Conversation with Subha: 

- Hari was able to generate the document on PROD. He wants us to submit a low priority ticket to fix it in test. 
- We have not verified that this is fixed on PROD with the end users yet. 
- I asked Hari to add work notes to the INC to better understand our next steps.

**Comment by SubhaShroff** [comment]
### Update:
@Nadin-Nader  @TracyLinder 

1. As we saw in today's call, on PROD, Jaclyn or Greg are not getting 'Can't find the file ..' error. On other thought, I wonder if its folder specific RSN-12926863 referring to the screenshot given in the AC. 

Will need to check particularly for this RSN on PROD, before concluding.

2. And then we still have this error on DEV/TEST environments, when I try. I believe that is related to network path connectivity access. 

Thank you.
